FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npm run db:generate

# Build the bank-webhook application
RUN npm run build --filter=bank-webhook

# Set working directory to bank-webhook
WORKDIR /usr/src/app/apps/bank-webhook

# Expose the port (bank-webhook runs on port 3003)
EXPOSE 3003

CMD ["npm", "start"] 