name: Build and Deploy Both Applications

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push user-app
      - name: Build and Push User App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user-app
          push: true
          tags: akashchakraborty56/servepay-user-app:latest

      # Build and push bank-webhook
      - name: Build and Push Bank Webhook
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.bank-webhook
          push: true
          tags: akashchakraborty56/servepay-bank-webhook:latest

      # Verify pushed images
      - name: Verify Pushed Images
        run: |
          docker pull akashchakraborty56/servepay-user-app:latest
          docker pull akashchakraborty56/servepay-bank-webhook:latest

      # Setup SSH for deployment
      - name: Setup SSH Key
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "SSH key setup completed"

      # Deploy both applications to EC2
      - name: Deploy Applications to EC2
        run: |
          echo "Deploying both applications..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "Starting deployment of both applications..."
            
            # Pull latest images
            sudo docker pull akashchakraborty56/servepay-user-app:latest
            sudo docker pull akashchakraborty56/servepay-bank-webhook:latest
            
            # Stop and remove existing containers
            sudo docker stop user-app || echo "No existing user-app container to stop"
            sudo docker rm user-app || echo "No existing user-app container to remove"
            sudo docker stop bank-webhook || echo "No existing bank-webhook container to stop"
            sudo docker rm bank-webhook || echo "No existing bank-webhook container to remove"
            
            # Start user-app container with NextAuth environment variables
            sudo docker run -d \
              --name user-app \
              -p 3000:3000 \
              --restart unless-stopped \
              -e NEXTAUTH_URL=http://${{ secrets.SSH_HOST }}:3000 \
              -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              akashchakraborty56/servepay-user-app:latest
            
            # Start bank-webhook container
            sudo docker run -d \
              --name bank-webhook \
              -p 3003:3003 \
              --restart unless-stopped \
              akashchakraborty56/servepay-bank-webhook:latest
            
            echo "Deployment completed successfully"
            echo "User App running on port 3000"
            echo "Bank Webhook running on port 3003"
            
            # Show running containers
            sudo docker ps
          EOF
