name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Prepare Dockerfile
        run: cp ./docker/Dockerfile.user-app ./Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: akashchakraborty56/servepay

      - name: Verify Pushed Image
        run: docker pull akashchakraborty56/servepay:latest

      - name: Validate SSH Key
        run: |
          echo "Validating SSH key format..."
          if [ -z "${{ secrets.SSH_KEY }}" ]; then
            echo "ERROR: SSH_KEY secret is empty or not set"
            exit 1
          fi
          echo "${{ secrets.SSH_KEY }}" | ssh-keygen -l -f /dev/stdin || echo "SSH key format validation failed"

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            echo "SSH connection successful"
            whoami
            pwd

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            echo "Starting deployment..."
            sudo docker pull akashchakraborty56/servepay:latest
            sudo docker stop web-app || echo "No existing container to stop"
            sudo docker rm web-app || echo "No existing container to remove"
            sudo docker run -d --name web-app -p 3005:3000 akashchakraborty56/servepay:latest
            echo "Deployment completed successfully"
